### ISSUE TITLE
Set Float Voltage or Output Current

### ISSUE THREAD

**Issue by spilegi** [TripitakaBC/ampinvt_esphome#3]
Hi,

Just stumbled across this.  Been trying to create something like this for a while, but did not have the technical skills, and was trying to use standard modbus utilities.

The biggest limitations of Charge Controllers like this is once set to Li-ion, you can't set them to charge to 28.8 then float at 27.2.

Is it possible to change the Floating voltage  and possible charging amps on the device using this?  If possible, we could use HA Automation in conjunction with a smart BMS to reduce the charging voltage to float the batteries, or reduce the charging amperage.   Essentially replicating Victron DVCC functionality.

**Comment by TripitakaBC** [comment]
If you take a look at the communications documents that I posted, you will find that there is no command to set the parameters you are looking to change via the modbus interface. While some parameters can be set this way, it doesn't look like your use case is among them.

Perhaps try the manufacturers directly; I found them to be very responsive via email during Chinese working hours.

**Comment by spilegi** [comment]
Thanks for the update.  I'll give them a try.  I've implemented this project into my HA, and it's working great.  Thanks for all your hard work!
